#!/bin/bash

declare arch=$(uname -m)
declare conda_mirror="https://repo.anaconda.com/miniconda"
declare conda_script="Miniconda3-py39_4.11.0-MacOSX-${arch}.sh"

declare app_prefix="$2/JupyterLab.app"
declare env_installer="${app_prefix}/Contents/Resources/env_installer"
declare conda_prefix="${app_prefix}/Contents/Resources/jlab_server"

/usr/bin/curl -L "${conda_mirror}/${conda_script}" --output "${env_installer}/${conda_script}"

/bin/bash "${env_installer}/${conda_script}" -b -p "${conda_prefix}"
"${conda_prefix}/bin/python3" -m pip install -r "${env_installer}/requirements.txt"

/bin/ln -s "${app_prefix}/Contents/Resources/app/jlab" /usr/local/bin/jlab
/bin/chmod 755 "${app_prefix}/Contents/Resources/app/jlab"

exit 0
